"""
Property-Based Tests for Tags Serialization Round-Trip via Pydantic Lead Model.

**Feature: fix-lead-enrichment-analytics, Property 3: Tags serialization round-trip**
**Validates: Requirements 5.4**

For any list of tag strings generated by the AI, writing them to the database
`tags` jsonb column and reading them back via the API (Pydantic Lead model)
should produce an equivalent list of strings.
"""

import sys
import os
import json

import pytest
from hypothesis import given, settings, strategies as st

sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

from routers.leads import Lead

# =============================================================================
# Generators / Strategies
# =============================================================================

# Realistic CRM tag strings (letters, numbers, dashes, underscores)
tag_st = st.text(
    alphabet=st.characters(whitelist_categories=("L", "N"), whitelist_characters="_- "),
    min_size=1,
    max_size=30,
).filter(lambda s: s.strip() != "")

tags_list_st = st.lists(tag_st, min_size=0, max_size=10)


# =============================================================================
# Property Test
# =============================================================================

class TestTagsRoundTripPydantic:
    """
    **Feature: fix-lead-enrichment-analytics, Property 3: Tags serialization round-trip**
    **Validates: Requirements 5.4**
    """

    @settings(max_examples=100)
    @given(tags=tags_list_st)
    def test_tags_pydantic_round_trip(self, tags):
        """
        **Feature: fix-lead-enrichment-analytics, Property 3: Tags serialization round-trip**
        **Validates: Requirements 5.4**

        For any list of tag strings, constructing a Lead with those tags,
        serializing to JSON (simulating API response), and deserializing back
        should produce the original tag list.
        """
        lead_data = {
            "id": "00000000-0000-0000-0000-000000000001",
            "full_name": "Test Lead",
            "phone": "+5511999999999",
            "created_at": "2025-01-01T00:00:00+00:00",
            "tags": tags,
        }

        lead = Lead(**lead_data)

        # Simulate the full API round-trip: model -> JSON string -> dict
        json_str = lead.model_dump_json()
        restored = json.loads(json_str)

        assert restored["tags"] == tags, (
            f"Tags round-trip failed.\n"
            f"  Original: {tags}\n"
            f"  Restored: {restored['tags']}"
        )
