/**
 * Property-Based Tests for Lead Tags Hook
 * 
 * Tests the tag management system for lead classification.
 */

import { describe, it, expect } from 'vitest';
import * as fc from 'fast-check';
import {
  isValidTagTimestamp,
  createTagWithTimestamp,
} from '../useLeadTags';
import type { LeadTagCategory, TagCreator } from '@/lib/temperature-config';

// ============================================
// Arbitraries (Generators)
// ============================================

/**
 * Generator for valid tag categories
 */
const tagCategoryArb: fc.Arbitrary<LeadTagCategory> = fc.constantFrom(
  'temperature',
  'interest',
  'behavior',
  'custom'
);

/**
 * Generator for tag creators
 */
const tagCreatorArb: fc.Arbitrary<TagCreator> = fc.constantFrom('ai', 'user');

/**
 * Generator for valid tag names
 */
const tagNameArb = fc.string({ minLength: 1, maxLength: 100 }).filter(s => s.trim().length > 0);

/**
 * Generator for optional tag values
 */
const tagValueArb = fc.option(fc.string({ maxLength: 500 }), { nil: undefined });

/**
 * Generator for confidence scores (0-1)
 */
const confidenceArb = fc.option(
  fc.float({ min: 0, max: 1, noNaN: true }),
  { nil: undefined }
);

/**
 * Generator for valid UUIDs
 */
const uuidArb = fc.uuid();

/**
 * Generator for past timestamps (not in the future)
 */
const pastTimestampArb = fc.date({
  min: new Date('2020-01-01'),
  max: new Date(),
}).filter(d => !isNaN(d.getTime()));

/**
 * Generator for future timestamps (invalid)
 */
const futureTimestampArb = fc.date({
  min: new Date(Date.now() + 1000), // 1 second in the future
  max: new Date(Date.now() + 365 * 24 * 60 * 60 * 1000), // 1 year in the future
});

/**
 * Generator for complete tag input
 */
const tagInputArb = fc.record({
  leadId: uuidArb,
  name: tagNameArb,
  category: tagCategoryArb,
  value: tagValueArb,
  confidence: confidenceArb,
  createdBy: fc.option(tagCreatorArb, { nil: undefined }),
});

// ============================================
// Property-Based Tests
// ============================================

describe('Lead Tags - Property Tests', () => {
  /**
   * **Feature: lead-filters-tags-system, Property 8: Tags Stored With Timestamp**
   * **Validates: Requirements 4.3**
   * 
   * For any tag generated by the AI, the stored tag record must include a valid 
   * timestamp (createdAt) that is not in the future.
   */
  describe('Property 8: Tags Stored With Timestamp', () => {
    it('should validate past timestamps as valid', () => {
      fc.assert(
        fc.property(
          pastTimestampArb,
          (timestamp) => {
            // Act: Validate the timestamp
            const isValid = isValidTagTimestamp(timestamp);

            // Assert: Past timestamps should be valid
            expect(isValid).toBe(true);
          }
        ),
        { numRuns: 100 }
      );
    });

    it('should reject future timestamps as invalid', () => {
      fc.assert(
        fc.property(
          futureTimestampArb,
          (timestamp) => {
            // Act: Validate the timestamp
            const isValid = isValidTagTimestamp(timestamp);

            // Assert: Future timestamps should be invalid
            expect(isValid).toBe(false);
          }
        ),
        { numRuns: 100 }
      );
    });

    it('should create tags with valid timestamps', () => {
      fc.assert(
        fc.property(
          tagInputArb,
          (input) => {
            // Act: Create a tag with timestamp
            const tag = createTagWithTimestamp(input);

            // Assert: Tag should have a valid timestamp
            expect(tag.createdAt).toBeInstanceOf(Date);
            expect(isValidTagTimestamp(tag.createdAt)).toBe(true);
          }
        ),
        { numRuns: 100 }
      );
    });

    it('should preserve all input properties in created tag', () => {
      fc.assert(
        fc.property(
          tagInputArb,
          (input) => {
            // Act: Create a tag
            const tag = createTagWithTimestamp(input);

            // Assert: All input properties should be preserved
            expect(tag.leadId).toBe(input.leadId);
            expect(tag.name).toBe(input.name);
            expect(tag.category).toBe(input.category);
            expect(tag.value).toBe(input.value);
            expect(tag.confidence).toBe(input.confidence);
            
            // createdBy defaults to 'ai' if not provided
            if (input.createdBy !== undefined) {
              expect(tag.createdBy).toBe(input.createdBy);
            } else {
              expect(tag.createdBy).toBe('ai');
            }
          }
        ),
        { numRuns: 100 }
      );
    });

    it('should generate unique IDs for each tag', () => {
      fc.assert(
        fc.property(
          fc.array(tagInputArb, { minLength: 2, maxLength: 10 }),
          (inputs) => {
            // Act: Create multiple tags
            const tags = inputs.map(input => createTagWithTimestamp(input));
            const ids = tags.map(tag => tag.id);

            // Assert: All IDs should be unique
            const uniqueIds = new Set(ids);
            expect(uniqueIds.size).toBe(ids.length);
          }
        ),
        { numRuns: 100 }
      );
    });

    it('should have timestamp close to current time', () => {
      fc.assert(
        fc.property(
          tagInputArb,
          (input) => {
            const before = new Date();
            
            // Act: Create a tag
            const tag = createTagWithTimestamp(input);
            
            const after = new Date();

            // Assert: Timestamp should be between before and after
            expect(tag.createdAt.getTime()).toBeGreaterThanOrEqual(before.getTime());
            expect(tag.createdAt.getTime()).toBeLessThanOrEqual(after.getTime());
          }
        ),
        { numRuns: 100 }
      );
    });
  });

  describe('Tag Category Validation', () => {
    it('should accept all valid tag categories', () => {
      fc.assert(
        fc.property(
          tagCategoryArb,
          (category) => {
            const input = {
              leadId: crypto.randomUUID(),
              name: 'Test Tag',
              category,
            };

            // Act: Create a tag
            const tag = createTagWithTimestamp(input);

            // Assert: Category should be preserved
            expect(tag.category).toBe(category);
            expect(['temperature', 'interest', 'behavior', 'custom']).toContain(tag.category);
          }
        ),
        { numRuns: 100 }
      );
    });
  });

  describe('Tag Creator Validation', () => {
    it('should accept all valid tag creators', () => {
      fc.assert(
        fc.property(
          tagCreatorArb,
          (createdBy) => {
            const input = {
              leadId: crypto.randomUUID(),
              name: 'Test Tag',
              category: 'custom' as LeadTagCategory,
              createdBy,
            };

            // Act: Create a tag
            const tag = createTagWithTimestamp(input);

            // Assert: Creator should be preserved
            expect(tag.createdBy).toBe(createdBy);
            expect(['ai', 'user']).toContain(tag.createdBy);
          }
        ),
        { numRuns: 100 }
      );
    });

    it('should default to ai creator when not specified', () => {
      const input = {
        leadId: crypto.randomUUID(),
        name: 'Test Tag',
        category: 'custom' as LeadTagCategory,
      };

      // Act: Create a tag without specifying creator
      const tag = createTagWithTimestamp(input);

      // Assert: Should default to 'ai'
      expect(tag.createdBy).toBe('ai');
    });
  });

  describe('Confidence Score Validation', () => {
    it('should preserve confidence scores in valid range', () => {
      fc.assert(
        fc.property(
          fc.float({ min: 0, max: 1, noNaN: true }),
          (confidence) => {
            const input = {
              leadId: crypto.randomUUID(),
              name: 'Test Tag',
              category: 'temperature' as LeadTagCategory,
              confidence,
            };

            // Act: Create a tag
            const tag = createTagWithTimestamp(input);

            // Assert: Confidence should be preserved
            expect(tag.confidence).toBe(confidence);
            expect(tag.confidence).toBeGreaterThanOrEqual(0);
            expect(tag.confidence).toBeLessThanOrEqual(1);
          }
        ),
        { numRuns: 100 }
      );
    });

    it('should handle undefined confidence', () => {
      const input = {
        leadId: crypto.randomUUID(),
        name: 'Test Tag',
        category: 'custom' as LeadTagCategory,
      };

      // Act: Create a tag without confidence
      const tag = createTagWithTimestamp(input);

      // Assert: Confidence should be undefined
      expect(tag.confidence).toBeUndefined();
    });
  });
});
