/**
 * Property-Based Tests for Agent Service - Compliance
 * **Feature: palmas-lake-agent-maria**
 * 
 * Tests for compliance requirements, specifically unauthorized discount promises
 */

import { describe, it, expect } from 'vitest';
import * as fc from 'fast-check';
import {
  GREETING_MESSAGE,
  LGPD_NOTICE,
  NAME_QUESTION,
  OBJECTION_RESPONSES,
  containsUnauthorizedDiscount,
  generateGreetingResponse,
  generateObjectionResponse,
  generateInfoResponse,
  generateNameAcknowledgment,
  generateQualificationResponse,
} from '../agent-service';
import type { QualificationState } from '@/types/maria-agent';

// ============================================
// Arbitraries (Generators)
// ============================================

// Generator for objection types
const objectionTypeArb = fc.constantFrom(
  'expensive',
  'thinking',
  'unknown_region',
  'family',
  'other_properties'
) as fc.Arbitrary<keyof typeof OBJECTION_RESPONSES>;

// Generator for info request types
const infoTypeArb = fc.constantFrom(
  'location',
  'financing',
  'delivery',
  'visit',
  'amenities',
  'differentials',
  'apartments',
  'commercial',
  'office',
  'flat'
) as fc.Arbitrary<'location' | 'financing' | 'delivery' | 'visit' | 'amenities' | 'differentials' | 'apartments' | 'commercial' | 'office' | 'flat'>;

// Generator for lead names
const leadNameArb = fc.string({ minLength: 2, maxLength: 50 })
  .filter(name => name.trim().length > 0);

// Generator for qualification states at different steps
const qualificationStateArb: fc.Arbitrary<QualificationState> = fc.record({
  step: fc.constantFrom(
    'name',
    'interest_type',
    'objective',
    'timeline',
    'region_knowledge',
    'contact_info',
    'complete'
  ),
  name: fc.option(fc.string({ minLength: 2, maxLength: 50 }), { nil: undefined }),
  interestType: fc.option(fc.constantFrom('apartamento', 'sala_comercial', 'office', 'flat'), { nil: undefined }),
  objective: fc.option(fc.constantFrom<'morar' | 'investir'>('morar', 'investir'), { nil: undefined }),
  timeline: fc.option(fc.constantFrom('imediato', 'curto_prazo', 'medio_prazo', 'longo_prazo'), { nil: undefined }),
  knowsRegion: fc.option(fc.boolean(), { nil: undefined }),
  isFromPalmas: fc.option(fc.boolean(), { nil: undefined }),
  phone: fc.option(fc.string({ minLength: 10, maxLength: 11 }), { nil: undefined }),
  email: fc.option(fc.emailAddress(), { nil: undefined }),
});

// Generator for texts that contain discount promises (for testing detection)
const discountPromiseArb = fc.constantFrom(
  'desconto de 10%',
  'desconto especial para você',
  'vou dar desconto',
  'posso dar desconto',
  'desconto garantido',
  '15% de desconto',
  '20 por cento de desconto'
);

// Generator for text with discount promise embedded
const textWithDiscountArb = fc.tuple(
  fc.string({ minLength: 0, maxLength: 30 }),
  discountPromiseArb,
  fc.string({ minLength: 0, maxLength: 30 })
).map(([prefix, discount, suffix]) => `${prefix} ${discount} ${suffix}`);

// Generator for safe text without discount promises
const safeTextArb = fc.string({ minLength: 1, maxLength: 200 })
  .filter(text => !containsUnauthorizedDiscount(text));

// ============================================
// Property Tests - Compliance
// ============================================

describe('Agent Service - Compliance Property Tests', () => {
  /**
   * **Feature: palmas-lake-agent-maria, Property 7: Compliance - Sem Promessas de Desconto**
   * **Validates: Requirements 11.2**
   * 
   * *For any* response generated by the agent, it should not contain unauthorized discount promises
   */
  describe('Property 7: Compliance - Sem Promessas de Desconto', () => {
    it('should not contain discount promises in greeting messages', () => {
      fc.assert(
        fc.property(fc.constant(null), () => {
          const response = generateGreetingResponse();
          
          for (const message of response.messages) {
            expect(containsUnauthorizedDiscount(message)).toBe(false);
          }
        }),
        { numRuns: 100 }
      );
    });

    it('should not contain discount promises in objection responses', () => {
      fc.assert(
        fc.property(objectionTypeArb, (objectionType) => {
          const response = generateObjectionResponse(objectionType);
          
          for (const message of response.messages) {
            expect(containsUnauthorizedDiscount(message)).toBe(false);
          }
        }),
        { numRuns: 100 }
      );
    });

    it('should not contain discount promises in info responses', () => {
      fc.assert(
        fc.property(infoTypeArb, (infoType) => {
          const response = generateInfoResponse(infoType);
          
          for (const message of response.messages) {
            expect(containsUnauthorizedDiscount(message)).toBe(false);
          }
        }),
        { numRuns: 100 }
      );
    });

    it('should not contain discount promises in name acknowledgments', () => {
      fc.assert(
        fc.property(leadNameArb, (name) => {
          const acknowledgment = generateNameAcknowledgment(name);
          
          expect(containsUnauthorizedDiscount(acknowledgment)).toBe(false);
        }),
        { numRuns: 100 }
      );
    });

    it('should not contain discount promises in qualification responses', () => {
      fc.assert(
        fc.property(qualificationStateArb, (state) => {
          const response = generateQualificationResponse(state);
          
          for (const message of response.messages) {
            expect(containsUnauthorizedDiscount(message)).toBe(false);
          }
        }),
        { numRuns: 100 }
      );
    });

    it('should not contain discount promises in static messages', () => {
      fc.assert(
        fc.property(fc.constant(null), () => {
          // Test all static messages
          expect(containsUnauthorizedDiscount(GREETING_MESSAGE)).toBe(false);
          expect(containsUnauthorizedDiscount(LGPD_NOTICE)).toBe(false);
          expect(containsUnauthorizedDiscount(NAME_QUESTION)).toBe(false);
          
          // Test all objection responses
          for (const response of Object.values(OBJECTION_RESPONSES)) {
            expect(containsUnauthorizedDiscount(response)).toBe(false);
          }
        }),
        { numRuns: 100 }
      );
    });

    it('should detect discount promises when present in text', () => {
      fc.assert(
        fc.property(textWithDiscountArb, (text) => {
          expect(containsUnauthorizedDiscount(text)).toBe(true);
        }),
        { numRuns: 100 }
      );
    });

    it('should not flag safe text as containing discount promises', () => {
      fc.assert(
        fc.property(safeTextArb, (text) => {
          expect(containsUnauthorizedDiscount(text)).toBe(false);
        }),
        { numRuns: 100 }
      );
    });
  });
});

// ============================================
// Unit Tests - Discount Detection
// ============================================

describe('Agent Service - Discount Detection Unit Tests', () => {
  describe('containsUnauthorizedDiscount', () => {
    it('should detect "desconto de X%"', () => {
      expect(containsUnauthorizedDiscount('Vou te dar um desconto de 10%')).toBe(true);
    });

    it('should detect "desconto especial"', () => {
      expect(containsUnauthorizedDiscount('Tenho um desconto especial para você')).toBe(true);
    });

    it('should detect "vou dar desconto"', () => {
      expect(containsUnauthorizedDiscount('Vou dar desconto nessa unidade')).toBe(true);
    });

    it('should detect "posso dar desconto"', () => {
      expect(containsUnauthorizedDiscount('Posso dar desconto se fechar hoje')).toBe(true);
    });

    it('should detect "desconto garantido"', () => {
      expect(containsUnauthorizedDiscount('Desconto garantido de 5%')).toBe(true);
    });

    it('should detect "X por cento de desconto"', () => {
      expect(containsUnauthorizedDiscount('15 por cento de desconto')).toBe(true);
    });

    it('should NOT flag normal price discussions', () => {
      expect(containsUnauthorizedDiscount('O valor é R$ 5.237.904,00')).toBe(false);
    });

    it('should NOT flag mentions of negotiation without discount promise', () => {
      expect(containsUnauthorizedDiscount('Vou transferir para o comercial para negociação')).toBe(false);
    });

    it('should NOT flag competitive pricing mentions', () => {
      expect(containsUnauthorizedDiscount('Nossos valores são competitivos')).toBe(false);
    });

    it('should be case insensitive', () => {
      expect(containsUnauthorizedDiscount('DESCONTO ESPECIAL')).toBe(true);
    });

    it('should handle accents', () => {
      expect(containsUnauthorizedDiscount('desconto garantido')).toBe(true);
    });
  });
});
