-- Migration 019: Semantic Cache with pgvector
-- Stores AI response embeddings for FAQ-like questions to avoid redundant LLM calls.
-- Embeddings generated by gemini-embedding-2-preview (truncated to 768 dimensions via MRL).

-- 1. Enable pgvector extension (idempotent)
CREATE EXTENSION IF NOT EXISTS vector WITH SCHEMA extensions;

-- 2. Create semantic_cache table
CREATE TABLE IF NOT EXISTS "palmaslake-agno".semantic_cache (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    question text NOT NULL,
    answer text NOT NULL,
    embedding vector(768) NOT NULL,
    qualification_step text NOT NULL DEFAULT 'name',
    channel text NOT NULL DEFAULT 'whatsapp',
    prompt_hash text NOT NULL DEFAULT '',
    hit_count int NOT NULL DEFAULT 0,
    created_at timestamptz NOT NULL DEFAULT now()
);

-- 3. IVFFlat index for fast cosine similarity search
-- lists=100 is good for up to ~100k rows; adjust if cache grows larger
CREATE INDEX IF NOT EXISTS idx_semantic_cache_embedding
    ON "palmaslake-agno".semantic_cache
    USING ivfflat (embedding vector_cosine_ops)
    WITH (lists = 100);

-- 4. Index for TTL cleanup queries
CREATE INDEX IF NOT EXISTS idx_semantic_cache_created_at
    ON "palmaslake-agno".semantic_cache (created_at);

-- 5. Index for prompt_hash invalidation
CREATE INDEX IF NOT EXISTS idx_semantic_cache_prompt_hash
    ON "palmaslake-agno".semantic_cache (prompt_hash);

-- 6. RPC function: match_semantic_cache
-- Returns the best matching cached answer if cosine similarity > threshold.
-- Filters by qualification_step, channel, prompt_hash, and TTL (7 days).
CREATE OR REPLACE FUNCTION "palmaslake-agno".match_semantic_cache(
    query_embedding vector(768),
    match_threshold float DEFAULT 0.92,
    match_step text DEFAULT 'name',
    match_channel text DEFAULT 'whatsapp',
    match_prompt_hash text DEFAULT '',
    max_ttl_days int DEFAULT 7
)
RETURNS TABLE (
    id uuid,
    question text,
    answer text,
    similarity float
)
LANGUAGE plpgsql
AS $$
BEGIN
    RETURN QUERY
    SELECT
        sc.id,
        sc.question,
        sc.answer,
        1 - (sc.embedding <=> query_embedding) AS similarity
    FROM "palmaslake-agno".semantic_cache sc
    WHERE sc.qualification_step = match_step
      AND sc.channel = match_channel
      AND sc.prompt_hash = match_prompt_hash
      AND sc.created_at > now() - (max_ttl_days || ' days')::interval
      AND 1 - (sc.embedding <=> query_embedding) > match_threshold
    ORDER BY sc.embedding <=> query_embedding
    LIMIT 1;
END;
$$;

-- 7. RPC function: increment hit count after a cache hit
CREATE OR REPLACE FUNCTION "palmaslake-agno".increment_cache_hit(cache_id uuid)
RETURNS void
LANGUAGE sql
AS $$
    UPDATE "palmaslake-agno".semantic_cache
    SET hit_count = hit_count + 1
    WHERE id = cache_id;
$$;

-- 8. Cleanup function: delete expired entries (run via cron or manually)
CREATE OR REPLACE FUNCTION "palmaslake-agno".cleanup_semantic_cache(ttl_days int DEFAULT 7)
RETURNS int
LANGUAGE plpgsql
AS $$
DECLARE
    deleted_count int;
BEGIN
    DELETE FROM "palmaslake-agno".semantic_cache
    WHERE created_at < now() - (ttl_days || ' days')::interval;
    GET DIAGNOSTICS deleted_count = ROW_COUNT;
    RETURN deleted_count;
END;
$$;

-- 9. RLS: allow service role full access (API uses service key)
ALTER TABLE "palmaslake-agno".semantic_cache ENABLE ROW LEVEL SECURITY;

CREATE POLICY "service_role_all" ON "palmaslake-agno".semantic_cache
    FOR ALL
    TO service_role
    USING (true)
    WITH CHECK (true);
